from comfy_api.latest import io

from .region_types import MAX_REGIONS


COLOR_DICT = io.Custom("COLOR_DICT")
REGIONAL_COLOR_REGION = io.Custom("REGIONAL_COLOR_REGION")
REGIONAL_COLOR_REGIONS = io.Custom("REGIONAL_COLOR_REGIONS")
REGIONAL_COLOR_HOOKS = io.Hooks

__all__ = [
    "COLOR_DICT",
    "MAX_REGIONS",
    "REGIONAL_COLOR_REGION",
    "REGIONAL_COLOR_REGIONS",
    "REGIONAL_COLOR_HOOKS",
]
